name: build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make -j4
      - name: Check CLI
        run: ./rom --help
